title: Windows Internals Blog
description: "Blog about my tries in Windows Reverse Engineering"
author:
  name: "truebad0ur"
  #email: "someone@somewebsite.somedomain"
  #url: ""

baseurl: /

source: .
destination: ./_site
#permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
#  - jekyll-paginate-v2
  - jekyll-sitemap
#  - jekyll-polyglot

# Custom variables
owner : "truebad0ur"
year : "2022"
